#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import cv2
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from perception.tabletopseg3d.src.camera.realsense_capture import (  # noqa: E402
    build_runtime,
    enumerate_devices,
    get_aligned_frame_bundle,
    intrinsics_to_dict,
    stop_runtimes,
)


MIN_POSE_CORRESPONDENCES = 6


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Basic ChArUco detection with RealSense.")
    parser.add_argument("--list-devices", action="store_true", help="List connected RealSense devices and exit.")
    parser.add_argument("--serial", type=str, default=None, help="Target RealSense serial number.")
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument(
        "--color-only",
        action="store_true",
        help="Use color-only streaming. Recommended for high-resolution board calibration on D435i.",
    )
    parser.add_argument("--warmup", type=int, default=15, help="Warmup frames before detection.")
    parser.add_argument("--frames", type=int, default=0, help="Process N frames then exit; 0 means run until quit.")
    parser.add_argument("--no-display", action="store_true", help="Disable OpenCV display window.")
    parser.add_argument("--dictionary", type=str, default="DICT_4X4_50")
    parser.add_argument("--squares-x", type=int, default=5, help="Number of chessboard squares along X.")
    parser.add_argument("--squares-y", type=int, default=7, help="Number of chessboard squares along Y.")
    parser.add_argument("--square-length-mm", type=float, default=25.0)
    parser.add_argument("--marker-length-mm", type=float, default=18.0)
    parser.add_argument(
        "--legacy-pattern",
        action="store_true",
        help="Enable legacy ChArUco board pattern compatibility for boards generated by older OpenCV versions.",
    )
    parser.add_argument("--save-dir", type=Path, default=None, help="Optional directory to save last overlay/json.")
    return parser.parse_args()


def intrinsics_to_camera_matrix(intr: dict[str, Any]) -> tuple[np.ndarray, np.ndarray]:
    camera_matrix = np.array(
        [
            [intr["fx"], 0.0, intr["ppx"]],
            [0.0, intr["fy"], intr["ppy"]],
            [0.0, 0.0, 1.0],
        ],
        dtype=np.float32,
    )
    dist_coeffs = np.array(intr["coeffs"], dtype=np.float32)
    return camera_matrix, dist_coeffs


def detect_markers_only(color_bgr: np.ndarray, dictionary: Any) -> tuple[list[Any], Any]:
    gray = cv2.cvtColor(color_bgr, cv2.COLOR_BGR2GRAY)
    if hasattr(cv2.aruco, "detectMarkers"):
        return cv2.aruco.detectMarkers(gray, dictionary)[:2]
    if hasattr(cv2.aruco, "ArucoDetector"):
        aruco_detector = cv2.aruco.ArucoDetector(dictionary)
        return aruco_detector.detectMarkers(gray)[:2]
    raise RuntimeError("OpenCV aruco marker detector API is not available in this environment.")


def get_color_only_frame_bundle(
    runtime: Any,
    retries: int = 5,
    retry_sleep_sec: float = 0.2,
    timeout_ms: int = 5000,
) -> dict[str, Any]:
    last_error: RuntimeError | None = None
    frames = None
    color_frame = None
    for _ in range(max(int(retries), 1)):
        try:
            frames = runtime.pipeline.wait_for_frames(int(timeout_ms))
            color_frame = frames.get_color_frame()
            if color_frame:
                break
            last_error = RuntimeError(
                f"Missing color frame from RealSense pipeline {runtime.info.serial_number}."
            )
        except RuntimeError as exc:
            last_error = exc
        if retry_sleep_sec > 0:
            import time

            time.sleep(float(retry_sleep_sec))

    if frames is None or not color_frame:
        raise last_error or RuntimeError(
            f"Missing color frame from RealSense pipeline {runtime.info.serial_number}."
        )

    color = np.asanyarray(color_frame.get_data())
    color_intrinsics = color_frame.profile.as_video_stream_profile().get_intrinsics()
    return {
        "serial_number": runtime.info.serial_number,
        "device_name": runtime.info.name,
        "firmware_version": runtime.info.firmware_version,
        "product_line": runtime.info.product_line,
        "usb_type_descriptor": runtime.info.usb_type_descriptor,
        "color": color,
        "timestamp_ms": frames.get_timestamp(),
        "frame_number": frames.get_frame_number(),
        "color_intrinsics": intrinsics_to_dict(color_intrinsics),
    }


def build_board(args: argparse.Namespace) -> tuple[Any, Any]:
    # Build the exact ChArUco board model that later detection and pose estimation refer to.
    if not hasattr(cv2.aruco, args.dictionary):
        raise RuntimeError(f"Unsupported aruco dictionary: {args.dictionary}")
    dictionary_id = getattr(cv2.aruco, args.dictionary)
    if hasattr(cv2.aruco, "getPredefinedDictionary"):
        dictionary = cv2.aruco.getPredefinedDictionary(dictionary_id)
    elif hasattr(cv2.aruco, "Dictionary_get"):
        dictionary = cv2.aruco.Dictionary_get(dictionary_id)
    else:
        raise RuntimeError("OpenCV aruco dictionary API is not available in this environment.")
    if hasattr(cv2.aruco, "CharucoBoard_create"):
        board = cv2.aruco.CharucoBoard_create(
            args.squares_x,
            args.squares_y,
            args.square_length_mm / 1000.0,
            args.marker_length_mm / 1000.0,
            dictionary,
        )
    else:
        board = cv2.aruco.CharucoBoard(
            (args.squares_x, args.squares_y),
            args.square_length_mm / 1000.0,
            args.marker_length_mm / 1000.0,
            dictionary,
        )
    if args.legacy_pattern and hasattr(board, "setLegacyPattern"):
        board.setLegacyPattern(True)
    return dictionary, board


def board_center_offset_m(squares_x: int, squares_y: int, square_length_m: float) -> np.ndarray:
    return np.array(
        [
            float(squares_x) * float(square_length_m) / 2.0,
            float(squares_y) * float(square_length_m) / 2.0,
            0.0,
        ],
        dtype=np.float64,
    )


def detected_charuco_center_offset_m(
    board: Any,
    charuco_ids: np.ndarray | None,
    fallback_offset_xyz_m: np.ndarray | None,
) -> np.ndarray | None:
    """Return the center of the currently detected ChArUco sub-board in board coordinates.

    This is important for our setup because the physical calibration target is a 6x6 cut-out
    from a larger original board. The correct axis origin is therefore the center of the
    detected 25 ChArUco corners, not the geometric center of the original full board model.
    """

    if charuco_ids is None or len(charuco_ids) == 0:
        return fallback_offset_xyz_m
    if not hasattr(board, "getChessboardCorners"):
        return fallback_offset_xyz_m
    chessboard_corners = np.asarray(board.getChessboardCorners(), dtype=np.float64).reshape(-1, 3)
    ids = [int(v) for v in np.asarray(charuco_ids).flatten().tolist()]
    if not ids:
        return fallback_offset_xyz_m
    if min(ids) < 0 or max(ids) >= len(chessboard_corners):
        return fallback_offset_xyz_m
    return np.mean(chessboard_corners[ids], axis=0)


def _safe_draw_frame_axes(
    overlay: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    rvec: np.ndarray,
    tvec: np.ndarray,
    axis_length: float,
) -> None:
    try:
        axis_points = np.array(
            [
                [0.0, 0.0, 0.0],
                [axis_length, 0.0, 0.0],
                [0.0, axis_length, 0.0],
                [0.0, 0.0, axis_length],
            ],
            dtype=np.float32,
        )
        projected, _ = cv2.projectPoints(axis_points, rvec, tvec, camera_matrix, dist_coeffs)
        pts = projected.reshape(-1, 2)
        h, w = overlay.shape[:2]
        if np.all((pts[:, 0] >= 0) & (pts[:, 0] < w) & (pts[:, 1] >= 0) & (pts[:, 1] < h)):
            cv2.drawFrameAxes(overlay, camera_matrix, dist_coeffs, rvec, tvec, axis_length)
    except cv2.error:
        pass


def detect_charuco(
    color_bgr: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    dictionary: Any,
    board: Any,
    square_length_m: float,
    board_center_offset_xyz_m: np.ndarray | None = None,
) -> tuple[np.ndarray, dict[str, Any]]:
    # Detect markers/corners from a real image frame and return both visualization and pose metadata.
    gray = cv2.cvtColor(color_bgr, cv2.COLOR_BGR2GRAY)
    marker_corners, marker_ids = detect_markers_only(color_bgr, dictionary)
    overlay = color_bgr.copy()
    if marker_ids is not None and len(marker_ids) > 0:
        cv2.aruco.drawDetectedMarkers(overlay, marker_corners, marker_ids)

    result: dict[str, Any] = {
        "marker_count": 0 if marker_ids is None else int(len(marker_ids)),
        "charuco_corner_count": 0,
        "pose_ok": False,
        "pose_source": None,
        "pose_origin": "board_corner",
        "pose_reason": f"waiting_for_at_least_{MIN_POSE_CORRESPONDENCES}_correspondences",
    }

    if marker_ids is None or len(marker_ids) == 0:
        return overlay, result

    result["marker_ids"] = [int(v) for v in marker_ids.flatten().tolist()]
    result["marker_corners_px"] = [
        [[float(pt[0]), float(pt[1])] for pt in corners.reshape(-1, 2).tolist()]
        for corners in marker_corners
    ]

    charuco_corners = None
    charuco_ids = None
    if hasattr(cv2.aruco, "CharucoDetector"):
        detector = cv2.aruco.CharucoDetector(board)
        charuco_corners, charuco_ids, marker_corners, marker_ids = detector.detectBoard(gray)
    else:
        retval, charuco_corners, charuco_ids = cv2.aruco.interpolateCornersCharuco(
            marker_corners,
            marker_ids,
            gray,
            board,
            cameraMatrix=camera_matrix,
            distCoeffs=dist_coeffs,
        )
        if retval is None or retval < 1 or charuco_ids is None or charuco_corners is None:
            charuco_corners = None
            charuco_ids = None

    if charuco_ids is not None and charuco_corners is not None:
        result["charuco_corner_count"] = int(len(charuco_ids))
        result["charuco_ids"] = [int(v) for v in charuco_ids.flatten().tolist()]
        result["charuco_corners_px"] = [
            [float(pt[0]), float(pt[1])] for pt in charuco_corners.reshape(-1, 2).tolist()
        ]
        cv2.aruco.drawDetectedCornersCharuco(overlay, charuco_corners, charuco_ids, (0, 255, 0))

    if charuco_ids is not None and len(charuco_ids) >= MIN_POSE_CORRESPONDENCES:
        pose_ok = False
        rvec = None
        tvec = None
        if hasattr(cv2.aruco, "estimatePoseCharucoBoard"):
            pose_ok, rvec, tvec = cv2.aruco.estimatePoseCharucoBoard(
                charuco_corners,
                charuco_ids,
                board,
                camera_matrix,
                dist_coeffs,
                None,
                None,
            )
        elif hasattr(board, "matchImagePoints"):
            obj_points, img_points = board.matchImagePoints(charuco_corners, charuco_ids)
            if obj_points is not None and img_points is not None and len(obj_points) >= 4:
                pose_ok, rvec, tvec = cv2.solvePnP(
                    obj_points,
                    img_points,
                    camera_matrix,
                    dist_coeffs,
                    flags=cv2.SOLVEPNP_ITERATIVE,
                )
        if bool(pose_ok):
            center_offset_xyz_m = detected_charuco_center_offset_m(board, charuco_ids, board_center_offset_xyz_m)
            if center_offset_xyz_m is not None:
                rot_mat, _ = cv2.Rodrigues(rvec)
                tvec = tvec + rot_mat @ np.asarray(center_offset_xyz_m, dtype=np.float64).reshape(3, 1)
            axis_length = max(square_length_m * 2.0, 0.03)
            _safe_draw_frame_axes(overlay, camera_matrix, dist_coeffs, rvec, tvec, axis_length)
            result.update(
                {
                    "pose_ok": True,
                    "pose_source": "charuco",
                    "pose_origin": "detected_charuco_center",
                    "pose_reason": "ok",
                    "rvec": [float(v) for v in rvec.flatten()],
                    "tvec_m": [float(v) for v in tvec.flatten()],
                }
            )
            return overlay, result
    elif charuco_ids is not None:
        result["pose_reason"] = (
            f"charuco_corners={len(charuco_ids)}_lt_{MIN_POSE_CORRESPONDENCES}"
        )

    # Fallback: estimate board pose directly from detected marker corners.
    if marker_ids is not None and len(marker_ids) >= 2:
        board_for_pose = cv2.aruco.Board(board.getObjPoints(), dictionary, board.getIds())
        try:
            obj_points, img_points = board_for_pose.matchImagePoints(marker_corners, marker_ids)
        except cv2.error:
            obj_points, img_points = None, None
        if obj_points is not None and img_points is not None and len(obj_points) >= MIN_POSE_CORRESPONDENCES:
            pose_ok, rvec, tvec = cv2.solvePnP(
                obj_points,
                img_points,
                camera_matrix,
                dist_coeffs,
                flags=cv2.SOLVEPNP_ITERATIVE,
            )
            if bool(pose_ok):
                if board_center_offset_xyz_m is not None:
                    rot_mat, _ = cv2.Rodrigues(rvec)
                    tvec = tvec + rot_mat @ np.asarray(board_center_offset_xyz_m, dtype=np.float64).reshape(3, 1)
                axis_length = max(square_length_m * 2.0, 0.03)
                _safe_draw_frame_axes(overlay, camera_matrix, dist_coeffs, rvec, tvec, axis_length)
                result.update(
                    {
                        "pose_ok": True,
                        "pose_source": "marker_board",
                        "pose_origin": "board_center",
                        "pose_reason": "ok",
                        "rvec": [float(v) for v in rvec.flatten()],
                        "tvec_m": [float(v) for v in tvec.flatten()],
                    }
                )
        elif obj_points is not None:
            result["pose_reason"] = (
                f"marker_points={len(obj_points)}_lt_{MIN_POSE_CORRESPONDENCES}"
            )
    return overlay, result


def main() -> None:
    args = parse_args()
    if args.color_only and args.width == 640 and args.height == 480:
        args.width = 1920
        args.height = 1080
    devices = enumerate_devices()

    if args.list_devices:
        if not devices:
            print("No RealSense devices found.")
            return
        for dev in devices:
            print(json.dumps(dev.__dict__, ensure_ascii=True))
        return

    if not devices:
        raise RuntimeError("No RealSense devices found.")

    selected = None
    if args.serial is None:
        selected = devices[0]
    else:
        for dev in devices:
            if dev.serial_number == args.serial:
                selected = dev
                break
    if selected is None:
        raise RuntimeError(f"Target serial not found: {args.serial}")

    dictionary, board = build_board(args)
    runtime = build_runtime(
        selected,
        args.width,
        args.height,
        args.fps,
        enable_depth=not args.color_only,
        enable_color=True,
    )
    processed_frames = 0
    last_overlay: np.ndarray | None = None
    last_result: dict[str, Any] | None = None

    try:
        for _ in range(max(args.warmup, 0)):
            if args.color_only:
                get_color_only_frame_bundle(runtime)
            else:
                get_aligned_frame_bundle(runtime, depth_min_m=0.02, depth_max_m=1.5)

        while True:
            if args.color_only:
                bundle = get_color_only_frame_bundle(runtime)
            else:
                bundle = get_aligned_frame_bundle(runtime, depth_min_m=0.02, depth_max_m=1.5)
            camera_matrix, dist_coeffs = intrinsics_to_camera_matrix(bundle["color_intrinsics"])
            overlay, result = detect_charuco(
                bundle["color"],
                camera_matrix,
                dist_coeffs,
                dictionary,
                board,
                args.square_length_mm / 1000.0,
                board_center_offset_m(args.squares_x, args.squares_y, args.square_length_mm / 1000.0),
            )
            result.update(
                {
                    "serial_number": bundle["serial_number"],
                    "frame_number": int(bundle["frame_number"]),
                    "timestamp_ms": float(bundle["timestamp_ms"]),
                }
            )
            print(json.dumps(result, ensure_ascii=True), flush=True)

            status = (
                f"markers={result['marker_count']} "
                f"charuco={result['charuco_corner_count']} "
                f"pose={'yes' if result['pose_ok'] else 'no'}"
            )
            cv2.putText(
                overlay,
                status,
                (10, 30),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                (0, 255, 0) if result["pose_ok"] else (0, 200, 255),
                2,
                cv2.LINE_AA,
            )

            last_overlay = overlay
            last_result = result
            processed_frames += 1

            if not args.no_display:
                cv2.imshow("charuco_detection", overlay)
                key = cv2.waitKey(1) & 0xFF
                if key in (27, ord("q")):
                    break

            if args.frames > 0 and processed_frames >= args.frames:
                break

        if args.save_dir is not None and last_overlay is not None and last_result is not None:
            args.save_dir.mkdir(parents=True, exist_ok=True)
            cv2.imwrite(str(args.save_dir / "charuco_overlay.png"), last_overlay)
            (args.save_dir / "charuco_result.json").write_text(
                json.dumps(last_result, ensure_ascii=True, indent=2),
                encoding="utf-8",
            )
    finally:
        stop_runtimes([runtime])
        if not args.no_display:
            cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
